name: syncnote
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^9.3.11
  gap: ^3.0.1
  objectbox: ^4.0.0
  objectbox_flutter_libs: ^4.0.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  uuid: ^4.4.0

  path: any
  intl: any
  flutter_screenutil: ^5.9.1
  flutter_animate: ^4.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  objectbox_generator: ^4.0.0

flutter:
  uses-material-design: true
