name: melonote
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  connectme: ^2.2.3
  dart_promise: ^0.0.1+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.4.2
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  hexcolor: ^3.0.1
  intl: any
  loading_animation_widget: ^1.3.0
  network_info_plus: ^6.1.4
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.2.0
  path: any
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  toastification: ^2.3.0
  uuid: ^4.4.0
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^4.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/folder.svg
    - assets/images/dark_folder.svg
