name: syncnote
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_quill: ^10.8.4
  flutter_screenutil: ^5.9.1
  gap: ^3.0.1
  intl: any
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  path: any
  path_provider: ^2.1.3
  provider: ^6.1.2
  toast_notification: ^1.0.0
  toastification: ^2.3.0
  uuid: ^4.4.0
 

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^4.1.0

flutter:
  uses-material-design: true
